[project]
name = "django-old"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.0.3,<5.2",
    "whitenoise>=6.6.0",
    "django-debug-toolbar>=4.3.0",
    "django-extensions>=3.2.3",
    "ipython>=8.22.2",
    "django-silk>=5.1.0",
    "django-data-browser>=4.2.8",
    "beautifulsoup4>=4.12.3",
    "django-active-link>=0.1.8",
    "openpyxl>=3.1.2",
    "ez-address-parser>=0.2.5",
    "django-filter>=24.2",
    "psycopg2-binary>=2.9.9",
    "dj-database-url>=3.0.1",
    "python-dotenv>=1.2.1",
    "pandas>=2.3.3",
    "uvicorn>=0.38.0",
]


[dependency-groups]
dev = [
    "django-stubs>=6.0.1",
    "djlint>=1.36.4",
]

[tool.djlint]
profile = "django"
ignore = "T002,H030,H031,D018"
