# Generated by Django 5.2.8 on 2025-11-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("industry", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AB", "Alberta"),
                            ("BC", "British Columbia"),
                            ("MB", "Manitoba"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("NT", "Northwest Territories"),
                            ("NS", "Nova Scotia"),
                            ("NU", "Nunavut"),
                            ("ON", "Ontario"),
                            ("PE", "Prince Edward Island"),
                            ("QC", "Quebec"),
                            ("SK", "Saskatchewan"),
                            ("YT", "Yukon"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "yellow_pages_link",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "existence_status",
                    models.CharField(
                        choices=[
                            ("exists", "Exists"),
                            ("does_not_exist", "Does Not Exist"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ColdCallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "pick_up_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "yes"),
                            ("no", "no"),
                            ("ivr", "ivr"),
                            ("voicemail", "voicemail"),
                            ("not connecting", "not connecting"),
                        ],
                        default="no",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("had_owner_conversation", models.BooleanField()),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("no", "no"), ("yes", "yes"), ("meeting", "meeting")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "my_area_code_city",
                    models.CharField(
                        blank=True, default="Toronto", max_length=100, null=True
                    ),
                ),
                (
                    "product_selling",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("opening", models.CharField(blank=True, max_length=255, null=True)),
                ("objection", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.prospect",
                    ),
                ),
            ],
        ),
    ]
