# Generated by Django 5.1.14 on 2026-04-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='industry',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], max_length=100),
        ),
    ]
