# Generated by Django 5.1.14 on 2026-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_prospect_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldcallrecord',
            name='my_area_code_city',
        ),
        migrations.RemoveField(
            model_name='coldcallrecord',
            name='objection',
        ),
        migrations.RemoveField(
            model_name='coldcallrecord',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='coldcallrecord',
            name='product_selling',
        ),
        migrations.AlterField(
            model_name='coldcallrecord',
            name='outcome',
            field=models.CharField(blank=True, choices=[('no', 'no'), ('yes', 'yes'), ('meeting', 'meeting'), ('hang_up', 'hang up'), ('undefined', 'undefined')], max_length=255, null=True),
        ),
    ]
